

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  info:
    name: Info
    runs-on: ubuntu-latest
    outputs:
      mod_id: ${{steps.mod_id.outputs.value }}
      version: ${{steps.version.outputs.version }}
 
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Action 1
        id: mod_id
        uses: dreamli0/my-action@main
        with:
          hi-there: 'action_1'
          
      - name: Action 2
        id: action_2
        uses: ciplugins-poc/my-action@main
        with:
          who-to-greet: 'action_2'

      - name: Version
        id: version
        run: |
          echo "version=main" >> "$GITHUB_OUTPUT"

          
  output:
      name: Output Info
      runs-on: ubuntu-latest
      needs: [ info ]
      steps: 
        # - run: echo "${{needs.info.outputs.mod_id}} version ${{needs.info.outputs.version}};"
        - run: echo "name=${{ needs.info.outputs.mod_id }}-othervalues" >> $GITHUB_OUTPUT
        
